name: MacOS build
on: [push, pull_request, workflow_dispatch]
defaults:
  run:
    shell: pwsh

jobs:
  build:
    name: Runs on macOS
    runs-on: macOS-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.ps1 -Task Test
